name: run_on_main

# Only trigger, when the other workflow succeeded
on:
  workflow_run:
    workflows: ["pr-merged"]
    types:
      - completed
    branches: ["main"]

jobs:
  context:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
          fetch-tags: true

      - name: Semantic Release
        id: semantic_release
        uses: cycjimmy/semantic-release-action@v4
        with:
          semantic_version: 23
          extra_plugins: |
            semantic-release-export-data
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"
