name: Retag Image on Merge

on:
  push:
    branches:
      - main

jobs:
  context:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
          fetch-tags: true

      - name: echo PARENT_COMMITS
        run: git rev-parse HEAD^@

      - name: Get the HEAD SHA of the merged PR branch
        run: |
          # Get the parent commits of the merge commit
          PARENT_COMMITS=$(git rev-parse HEAD^@)

          # Extract the SHA of the PR branch (not the main branch)
          for COMMIT in $PARENT_COMMITS; do
            if ! git branch --contains "$COMMIT" | grep -q 'main'; then
              echo "PR_BRANCH_SHA=$COMMIT" >> $GITHUB_ENV
            fi
          done

      - name: Semantic Release
        id: semantic_release
        uses: cycjimmy/semantic-release-action@v4
        with:
          semantic_version: 23
          extra_plugins: |
            semantic-release-export-data
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"
