name: pull_request_target closed and merged
on:
  pull_request_target:
    types:
      - closed

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
          fetch-tags: true

      - name: Semantic Release
        id: semantic_release
        uses: cycjimmy/semantic-release-action@v4
        with:
          semantic_version: 23
          extra_plugins: |
            semantic-release-export-data
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Get previous commit
        id: prev-commit
        run: echo "sha=$(git rev-parse --verify HEAD^1)" >> $GITHUB_OUTPUT
      
      - name: print sha
        run: echo ${{ github.sha }}

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"

      - name: echo sha
        run: echo ${{ github.event.pull_request.head.sha}}

      - name: print previous commit
        run: echo ${{ steps.prev-commit.outputs.sha }}
      - run: |
          echo The PR was merged
